#
# Makefile for the input core drivers.
#

# Each configuration option enables a list of files.
# sensor drivers
obj-$(CONFIG_SENSORS_AKM8963)	+= ecompass/
obj-$(CONFIG_SENSORS_AL3320A)	+= al3320a/
obj-$(CONFIG_SENSORS_AL3320_EC)	+= al3320a_EC/
obj-$(CONFIG_HALL_SENSOR)       += hall/
